### PR TITLE
Add option to read a value from inside the secret for key/value json …

### PR DESCRIPTION
**Pull request by lasred**
…document secrets

*Issue #, if available:*

Address https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/11

*Description of changes:*

Add option to read a value from inside the secret for json document secrets

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by filipbekic01** [comment]
Much needed!

**Comment by kareem-elsayed** [comment]
We are in need of that feature ASAP

**Comment by wiltonfelix** [comment]
We are in need of that feature ASAP

**Review by yuriadams — APPROVED** [review]

**Review by LeandroFranciscato — APPROVED** [review]

**Comment by marcelobartsch** [comment]
@lasred , first of all, thank for the work on this issue, now , any plans to merge this request any time soon or at least provide a test image so we can test and provide better feedback on the solution proposed?

**Comment by shubydo** [comment]
@lasred Any updates on this? This is a feature our team is looking to utilize

**Comment by syscll** [comment]
Likewise, this is a very useful feature!

**Comment by filipbekic01** [comment]
Is this coming anytime soon? 🔢

**Comment by lasred** [comment]
We are addressing this feature request at high priority. We will publish an update when available.

**Review by joebaro — APPROVED** [review]

**Review by willtong1234 — APPROVED** [review]

**Pull request merged**
