### PR TITLE
Add imagePullSecrets to Helm chart

### LINKED ISSUE #192: Missing image pull Secrets to pull from private repo
this helm cannot be configured to pull images from private repository because it missing the use of imagePull secrets in its helm chart. Not sure why this was not noticed

Copy the public image to private repo as if you are a bank and then try it,

Do you also notice this bug when using a different secrets store provider (Vault/Azure/GCP...)? irrelavant

### PR DESCRIPTION
**Pull request by simonmarty**
Fixes #192

### CODE REVIEW

**Comment by simonmarty** [comment]
Tested with `imagePullSecrets: [{ name: mysecret }]`

```
    spec:
      serviceAccountName: release-name-secrets-store-csi-driver-provider-aws
      hostNetwork: false
      containers:
        - name: provider-aws-installer
          image: public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r2-42-ga2fd202-2023.03.03.20.03
          imagePullPolicy: IfNotPresent
          args:
            - --provider-volume=/etc/kubernetes/secrets-store-csi-providers
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - mountPath: /etc/kubernetes/secrets-store-csi-providers
              name: providervol
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: HostToContainer
      volumes:
        - name: providervol
          hostPath:
            path: /etc/kubernetes/secrets-store-csi-providers
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
      imagePullSecrets:
        - name: mysecret
      nodeSelector:
        kubernetes.io/os: linux
```

**Comment by evanshoshan** [comment]
Bumping this as it is needed for many helm deployments and was previously supported by version 0.0.4

**Review by danmancuso — APPROVED** [review]

**Comment by g-m-o-n-e-y** [comment]
@lasred / @mandydas - either of you have a second for a quick review/approval?

**Review by mandydas — APPROVED** [review]

**Comment by nxf5025** [comment]
When is this going to be released? We're still maintaining a fork, but would like to get back on track sooner rather than later

**Pull request merged**
